V1 of NTP service
distributed-technologies/services-ntp pull request #1
Opened 2021-08-12 10:52 UTC by klausenbusk

2021-08-12 16:28 UTC, jacobcrawford requested changes
Overall a good first solution. However, I need a little more information to do a more thorough review. 
Please provide a readme that answers the following questions:
What does the chart do in general?
What is the purpose of the daemonset?
What is the purpose of the deployment?

It is also good practice to provide a link that can be used to further understand what happens in the configuration files. :)

2021-08-12 16:28 UTC, jacobcrawford commented on .github/workflows/build-and-push-image.yml
> +  REGISTRY: ghcr.io
I am not sure that we actually want to use Github packages instead of Dockerhub, but this is a question for the senior architect. We will need to discuss this with Jakon Hviid to @MartinSchmidt

2021-08-12 16:28 UTC, jacobcrawford commented on chart/Chart.yaml
> +version: 0.1.0
We use "v" prefix on helm chart versions.

2021-08-12 16:28 UTC, jacobcrawford commented on chart/values.yaml
> +# Default values for chart.
Remove the comments from when the file was created.

2021-08-12 19:22 UTC, klausenbusk commented on .github/workflows/build-and-push-image.yml
> +  REGISTRY: ghcr.io
It is worth noticing the Docker Hub Rate Limiting when comparing the two registries.

> On November 20, 2020, rate limits anonymous and free authenticated use of Docker Hub went into effect. Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours. You can read here for more detailed information.

https://www.docker.com/increase-rate-limits

2021-08-13 06:59 UTC, klausenbusk commented on chart/Chart.yaml
> +version: 0.1.0
Apparently adding `v` isn't valid https://semver.org/#is-v123-a-semantic-version, `helm` and the underlying library is [quite forgiving](https://github.com/jetstack/cert-manager/issues/691#issuecomment-402526343) but other tooling [isn't](https://github.com/jetstack/cert-manager/issues/691#issuecomment-534953908).

Do we care?

2021-08-16 09:55 UTC, jacobcrawford commented on chart/Chart.yaml
> +version: 0.1.0
I think we need to conform to our own standards in this case. 
Though we might change it in the future if the "v" is not preferred!
You can create a story in Jira where you outline the cons of using the "v" prefix and then we can look at it when we have backlog grooming  :)

2021-08-16 12:06 UTC, jaxels10 commented
Could you put into words how we tested this? The issue we are sometimes facing is that Ceph monitors go out of sync cause of a CLOCK_SKEW error.

2021-08-17 04:41 UTC, klausenbusk commented
> Could you put into words how we tested this?

The best way to check this is running `chronyc tracking` in the DaemonSet pod:
```sh
$ chronyc tracking
Reference ID    : C1434FCA (ntp0.nl.uu.net)
Stratum         : 2
Ref time (UTC)  : Tue Aug 17 04:20:42 2021
System time     : 0.000039067 seconds fast of NTP time
Last offset     : +0.000038679 seconds
RMS offset      : 0.000118552 seconds
Frequency       : 7.658 ppm fast
Residual freq   : +0.001 ppm
Skew            : 0.033 ppm
Root delay      : 0.011127446 seconds
Root dispersion : 0.001022016 seconds
Update interval : 1038.0 seconds
Leap status     : Normal
```
*This was taken from my server, the output in the pods are slightly different*

`System time` shouldn't be to far off. The `System time` in the Deployments is likely a bit off as they can't synchronize the system time as we don't want two `chrony` instances on the same node to fight each other.

`chronyc sources -v` is another useful command worth mentioning:
```sh
$ chronyc sources -v

  .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
 / .- Source state '*' = current best, '+' = combined, '-' = not combined,
| /             'x' = may be in error, '~' = too variable, '?' = unusable.
||                                                 .- xxxx [ yyyy ] +/- zzzz
||      Reachability register (octal) -.           |  xxxx = adjusted offset,
||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
||                                \     |          |  zzzz = estimated error.
||                                 |    |           \
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
===============================================================================
^* ntp0.nl.uu.net                1  10   377    94   +246us[ +408us] +/- 5470us
^? ntp1.nl.uu.net                1  10     0    9d   +247ms[ +562us] +/- 5252us
^+ ntp-main-2.oma.be             1  10   377   874    -88us[  +62us] +/- 7685us
^+ ntp-main-1.oma.be             1   9   377   496    -44us[ +112us] +/- 7924us
```

2021-09-01 09:20 UTC, jacobcrawford commented on .github/workflows/build-and-push-image.yml
> +  REGISTRY: ghcr.io
We use ghcr as registry.

2021-09-10 08:03 UTC, jacobcrawford commented
@klausenbusk I can approve this if you change the version prefix.

2021-09-12 16:56 UTC, klausenbusk commented
> @klausenbusk I can approve this if you change the version prefix.

Done

2021-09-13 05:58 UTC, jacobcrawford approved these changes
LGTM

2021-09-13 07:55 UTC, merged